services:
  backend:
    volumes: !override
      - ./preprocessing:/preprocessing:ro
      - ./fragment_context_cache:/fragment_context_cache
    command: uvicorn main:app --workers 1 --host 0.0.0.0 --port 8000

  site:
    ports: !override []
